services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    restart: unless-stopped

    ports:
      - "3338:3338"
      - "3339:3339"

    environment:
      NODE_ENV: production
      PORT: 3338
      HTTPS_PORT: 3339

    command: pm2-runtime start index.js -i 3